StartupEvents.registry('item', event => {
    event.create('iron_sword_template').displayName('Iron Sword Template')
    event.create('iron_pickaxe_template').displayName('Iron Pickaxe Template')
    event.create('iron_axe_template').displayName('Iron Axe Template')
    event.create('iron_shovel_template').displayName('Iron Shovel Template')
    event.create('iron_hoe_template').displayName('Iron Hoe Template')
    event.create('diamond_sword_template').displayName('Diamond Sword Template')
    event.create('diamond_pickaxe_template').displayName('Diamond Pickaxe Template')
    event.create('diamond_axe_template').displayName('Diamond Axe Template')
    event.create('diamond_shovel_template').displayName('Diamond Shovel Template')
    event.create('diamond_hoe_template').displayName('Diamond Hoe Template')
    event.create('golden_sword_template').displayName('Golden Sword Template')
    event.create('golden_pickaxe_template').displayName('Golden Pickaxe Template')
    event.create('golden_axe_template').displayName('Golden Axe Template')
    event.create('golden_shovel_template').displayName('Golden Shovel Template')
    event.create('golden_hoe_template').displayName('Golden Hoe Template')
    event.create('diamond_dust').displayName('Diamond Dust')
    event.create('reinforced_string').displayName('Reinforced String')
    event.create('hardened_leather').displayName('Hardened Leather')
    event.create('golden_mattock_template').displayName('Golden Mattock Template')
    event.create('iron_mattock_template').displayName('Iron Mattock Template')
    event.create('diamond_mattock_template').displayName('Diamond Mattock Template')
    event.create('diamond_hardened_iron_ingot').displayName('Diamond Infused Iron Ingot')
    event.create('diamond_hardened_iron_sheet').displayName('Diamond Infused Iron Sheet')
    event.create('diamond_hardened_iron_nugget').displayName('Diamond Infused Iron Nugget')
    event.create('molten_iron').displayName('Molten Iron Ingot')
    event.create('sewing_needle', 'sword').displayName('Sewing Needle').attackDamageBaseline(-2.0).maxDamage(24)
    event.create('iron_hammer', 'sword').displayName('Iron Hammer').attackDamageBaseline(-2.0).maxDamage(12)
    event.create('plastic_pellets').displayName('Plastic Pellets')
    event.create('molten_plastic_pellets').displayName('Molten Plastic Pellets')
    event.create('plastic').displayName('Plastic')
})
StartupEvents.registry('fluid', event => {
    event.create('crude_oil')
        .thickTexture(0x1a1a1a)
        .bucketColor(0x1a1a1a)
        .displayName('Petroleum')
    event.create('liquid_naphtha')
        .thinTexture(0xc4ad2b)
        .bucketColor(0xc4ad2b)
        .displayName('Liquid Naphtha')
    event.create('liquid_ethylene')
        .thinTexture(0xE8E8FF)
        .bucketColor(0xE8E8FF)
        .displayName('Liquid Ethylene')
        .gaseous()
})